spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/quartz?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Mysql@123
    driver-class-name: com.mysql.jdbc.Driver
mybatis: 
  mapper-locations:
  - classpath:com/example/demo/mapper/*.xml
  type-aliases-package: com.example.demo.entity
    